export interface BorrowersInformation {
    // ID: number;
    // DateApplied: string;
    // EncodedBy: string;
    // AmountApplied: string;
    // DesiredTerm: string;
    // Purpose: string;
    // Based: string;
    // SeabasedAgency: string;
    // SeabasedAgencyRate: string;
    // SeabasedJoiningPort: string;
    // SeabasedPosition: string;
    // SeabasedContractTerm: string;
    // SeabsedMonthlySalary: string;
    // SeabasedPrincipal: string;
    // SeabasedYearsasSeafarer: string;
    // LandbasedAgency: string;
    // LandbasedAgencyRate: string;
    // LandbasedCountryBoundFor: string;
    // LandbasedPosition: string;
    // LandbasedContractTerm: string;
    // LandbasedMonthlySalary: string;
    // LandbasedEmployer: string;
    // LandbasedYearsasOFW: string;
    // BorrowerLastName: string;
    // BorrowerFirstName: string;
    // BorrowerMiddleName: string;
    // BorrowerBirthDate: string;
    // BorrowerGender: string;
    // BorrowerCivilStatus: string;
    // BorrowerPersonalEmailAddress: string;
    // BorrowerMobileNo: string;
    // BorrowerLandlineNo: string;
    // BorrowerSSSID: string;
    // BorrowerTINID: string;
    // BorrowerWebsiteorApplication: string;
    // BorrowerWebsiteApplicationName: string;
    // BorrowerWebsiteApplicationPhonestring: string;
    // BorrowerHomeOwnership: string;
    // BorrowerHomeOwnershipHowMuch: string;
    // BorrowerHomeAddress: string;
    // BorrowerHomeLengthofStay: string;
    // BorrowerHomeProvince: string;
    // BorrowerHomeCity: string;
    // BorrowerHomeBarangay: string;
    // BorrowerIsHomeAddressSametoProvincial: string;
    // BorrowerProvincialAddress: string;
    // BorrowerProvincialLengthofStay: string;
    // BorrowerProvincialProvince: string;
    // BorrowerProvincialCity: string;
    // BorrowerProvincialBarangay: string;
    // BorrowerWithSpouse: string;
    // BorrowerSpouseLastName: string;
    // BorrowerSpouseFirstName: string;
    // BorrowerSpouseMiddleName: string;
    // BorrowerSpouseBirthDate: string;
    // BorrowerSpousePersonalEmailAddress: string;
    // BorrowerSpouseMobileNo: string;
    // BorrowerSpouseFacebookName: string;
    // BorrowerSpouseHomeAddress: string;
    // BorrowerSpouseHomeLengthofStay: string;
    // BorrowerSpouseHomeProvince: string;
    // BorrowerSpouseCity: string;
    // BorrowerSpouseBarangay: string;
    // BorrowerSpouseEmployerName: string;
    // BorrowerSpouseEmployerHomeAddress: string;
    // BorrowerSpouseEmployerProvince: string;
    // BorrowerSpouseEmployerCity: string;
    // BorrowerSpouseEmployerBarangay: string;
    // BorrowerSpouseHomeOwnership: string;
    // BorrowerSpouseHomeOwnershipHowMuch: string;
    // BorrowerWithDependent: string;
    // Borrower1stDependentName: string;
    // Borrower1stDependentSchoolAttended: string;
    // Borrower1stDependentAge: string;
    // Borrower1stDependentMobileNo: string;
    // Borrower2ndDependentName: string;
    // Borrower2ndDependentSchoolAttended: string;
    // Borrower2ndDependentAge: string;
    // Borrower2ndDependentMobileNo: string;
    // Borrower3rdDependentName: string;
    // Borrower3rdDependentSchoolAttended: string;
    // Borrower3rdDependentAge: string;
    // Borrower3rdDependentMobileNo: string;
    // Borrower4thDependentName: string;
    // Borrower4thDependentSchoolAttended: string;
    // Borrower4thDependentAge: string;
    // Borrower4thDependentMobileNo: string;
    // Borrower5thDependentName: string;
    // Borrower5thDependentSchoolAttended: string;
    // Borrower5thDependentAge: string;
    // Borrower5thDependentMobileNo: string;
    // BorrowerWithCoBorrower: string;
    // BorrowerCoBorrowerLastName: string;
    // BorrowerCoBorrowerFirstName: string;
    // BorrowerCoBorrowerMiddleName: string;
    // BorrowerCoBorrowerFacebookName: string;
    // BorrowerCoBorrowerBirthDate: string;
    // BorrowerCoBorrowerPersonalEmailAddress: string;
    // BorrowerCoBorrowerMobileNo: string;
    // BorrowerCoBorrowerRelationshiptoApplicant: string;
    // BorrowerCoBorrowerHomeAddress: string;
    // BorrowerCoBorrowerHomeLengthofStay: string;
    // BorrowerCoBorrowerHomeProvince: string;
    // BorrowerCoBorrowerCity: string;
    // BorrowerCoBorrowerBarangay: string;
    // BorrowerCoBorrowerEmployerName: string;
    // BorrowerCoBorrowerEmployerHomeAddress: string;
    // BorrowerCoBorrowerEmployerProvince: string;
    // BorrowerCoBorrowerEmployerCity: string;
    // BorrowerCoBorrowerEmployerBarangay: string;
    // BorrowerCoBorrowerHomeOwnership: string;
    // BorrowerCoBorrowerHomeOwnershipHowMuch: string;
    // BorrowerFathersName: string;
    // BorrowerMothersName: string;
    // BorrowerParentsHomeAddress: string;
    // BorrowerParentsHomeProvince: string;
    // BorrowerParentsHomeCity: string;
    // BorrowerParentsHomeBarangay: string;
    // BorrowerParentsHomeLengthofStay: string;
    // BorrowerParentsMobileNo: string;
    // BorrowerParentsLandlineMobileNo: string;
    // Borrower1stRelativeName: string;
    // Borrower1stRelativeHomeAddress: string;
    // Borrower1stRelativeHomeProvince: string;
    // Borrower1stRelativeHomeCity: string;
    // Borrower1stRelativeHomeBarangay: string;
    // Borrower1stRelativeMobileNo: string;
    // Borrower1stRelativeRelationshiptoApplicant: string;
    // Borrower2ndRelativeName: string;
    // Borrower2ndRelativeHomeAddress: string;
    // Borrower2ndRelativeHomeProvince: string;
    // Borrower2ndRelativeHomeCity: string;
    // Borrower2ndRelativeHomeBarangay: string;
    // Borrower2ndRelativeMobileNo: string;
    // Borrower2ndRelativeRelationshiptoApplicant: string;
    // Borrower3rdRelativeName: string;
    // Borrower3rdRelativeHomeAddress: string;
    // Borrower3rdRelativeHomeProvince: string;
    // Borrower3rdRelativeHomeCity: string;
    // Borrower3rdRelativeHomeBarangay: string;
    // Borrower3rdRelativeMobileNo: string;
    // Borrower3rdRelativeRelationshiptoApplicant: string; 


AmountApplied: string;
Based: string;
Borrower1stDependentAge: string;
Borrower1stDependentMobileNo: string;
Borrower1stDependentName: string;
Borrower1stDependentSchoolAttended: string;
Borrower1stRelativeHomeAddressUnitStreetDoorBuilding: string;
Borrower1stRelativeHomeBarangay: string;
Borrower1stRelativeHomeCity: string;
Borrower1stRelativeHomeProvince: string;
Borrower1stRelativeMobileNo: string;
Borrower1stRelativeName: string;
Borrower1stRelativeRelationshiptoApplicant: string;
Borrower2ndDependentAge: string;
Borrower2ndDependentMobileNo: string;
Borrower2ndDependentName: string;
Borrower2ndDependentSchoolAttended: string;
Borrower2ndRelativeHomeAddressUnitStreetDoorBuilding: string;
Borrower2ndRelativeHomeBarangay: string;
Borrower2ndRelativeHomeCity: string;
Borrower2ndRelativeHomeProvince: string;
Borrower2ndRelativeMobileNo: string;
Borrower2ndRelativeName: string;
Borrower2ndRelativeRelationshiptoApplicant: string;
Borrower3rdDependentAge: string;
Borrower3rdDependentMobileNo: string;
Borrower3rdDependentName: string;
Borrower3rdDependentSchoolAttended: string;
Borrower3rdRelativeHomeAddressUnitStreetDoorBuilding: string;
Borrower3rdRelativeHomeBarangay: string;
Borrower3rdRelativeHomeCity: string;
Borrower3rdRelativeHomeProvince: string;
Borrower3rdRelativeMobileNo: string;
Borrower3rdRelativeName: string;
Borrower3rdRelativeRelationshiptoApplicant: string;
Borrower4thDependentAge: string;
Borrower4thDependentMobileNo: string;
Borrower4thDependentName: string;
Borrower4thDependentSchoolAttended: string;
Borrower5thDependentAge: string;
Borrower5thDependentMobileNo: string;
Borrower5thDependentName: string;
Borrower5thDependentSchoolAttended: string;
BorrowerBirthDate: string;
BorrowerCivilStatus: string;
BorrowerCoBorrowerBarangay: string;
BorrowerCoBorrowerBirthDate: string;
BorrowerCoBorrowerCity: string;
BorrowerCoBorrowerEmployerBarangay: string;
BorrowerCoBorrowerEmployerCity: string;
BorrowerCoBorrowerEmployerHomeAddress: string;
BorrowerCoBorrowerEmployerName: string;
BorrowerCoBorrowerEmployerProvince: string;
BorrowerCoBorrowerFacebookName: string;
BorrowerCoBorrowerFirstName: string;
BorrowerCoBorrowerHomeAddressUnitStreetDoorBuilding: string;
BorrowerCoBorrowerHomeLengthofStaymonths: string;
BorrowerCoBorrowerHomeOwnership: string;
BorrowerCoBorrowerHomeOwnershipHowMuch: string;
BorrowerCoBorrowerHomeProvince: string;
BorrowerCoBorrowerLastName: string;
BorrowerCoBorrowerMiddleName: string;
BorrowerCoBorrowerMobileNo: string;
BorrowerCoBorrowerPersonalEmailAddress: string;
BorrowerCoBorrowerRelationshiptoApplicant: string;
BorrowerFathersName: string;
BorrowerFirstName: string;
BorrowerGender: string;
BorrowerHomeAddressUnitStreetDoorBuilding: string;
BorrowerHomeBarangay: string;
BorrowerHomeCity: string;
BorrowerHomeLengthofStaymonths: string;
BorrowerHomeOwnership: string;
BorrowerHomeOwnershipHowMuchIfOwnedMortgageRented: string;
BorrowerHomeProvince: string;
BorrowerIsHomeAddressSametoProvincial: string;
BorrowerLandlineNo: string;
BorrowerLastName: string;
BorrowerMiddleName: string;
BorrowerMobileNo: string;
BorrowerMothersName: string;
BorrowerParentsHomeAddressUnitStreetDoorBuilding: string;
BorrowerParentsHomeBarangay: string;
BorrowerParentsHomeCity: string;
BorrowerParentsHomeLengthofStay: string;
BorrowerParentsHomeProvince: string;
BorrowerParentsLandlineNo: string;
BorrowerParentsMobileNo: string;
BorrowerPersonalEmailAddress: string;
BorrowerProvincialAddressUnitStreetDoorBuilding: string;
BorrowerProvincialBarangay: string;
BorrowerProvincialCity: string;
BorrowerProvincialLengthofStaymonths: string;
BorrowerProvincialProvince: string;
BorrowerSSSID: string;
BorrowerSpouseBarangay: string;
BorrowerSpouseBirthDate: string;
BorrowerSpouseCity: string;
BorrowerSpouseEmployerBarangay: string;
BorrowerSpouseEmployerCity: string;
BorrowerSpouseEmployerHomeAddressUnitStreetDoorBuilding: string;
BorrowerSpouseEmployerName: string;
BorrowerSpouseEmployerProvince: string;
BorrowerSpouseFacebookName: string;
BorrowerSpouseFirstName: string;
BorrowerSpouseHomeLengthofStay: string;
BorrowerSpouseHomeOwnership: string;
BorrowerSpouseHomeOwnershipHowMuch: string;
BorrowerSpouseHomeProvince: string;
BorrowerSpouseLastName: string;
BorrowerSpouseMiddleName: string;
BorrowerSpouseMobileNo: string;
BorrowerSpousePersonalEmailAddress: string;
BorrowerTINID: string;
BorrowerWebsiteApplicationName: string;
BorrowerWebsiteApplicationPhoneNo: string;
BorrowerWebsiteorApplication: string;
BorrowerWithCoBorrower: string;
BorrowerWithDependent: string;
BorrowerWithSpouse: string;
DateApplied: string;
DesiredTermmonths: string;
EncodedBy: string;
ID: number;
LandbasedAgency: string;
LandbasedAgencyRate: string;
LandbasedContractTermmonths: string;
LandbasedCountryBoundFor: string;
LandbasedEmployer: string;
LandbasedMonthlySalary: string;
LandbasedPosition: string;
LandbasedYearsasOFW: string;
Purpose: string;
SeabasedAgency: string;
SeabasedAgencyRate: string;
SeabasedContractTermmonths: string;
SeabasedJoiningPort: string;
SeabasedPosition: string;
SeabasedPrincipal: string;
SeabasedYearsasSeafarer: string;
SeabsedMonthlySalary: string;
AmountAppliedConverted: number;
Agency: string;
BorrowerSpouseHomeAddressUnitStreetDoorBuilding: string;
// BorrowerFullName: string;
}
